resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: git                      
      path: jfrog/shipaio  
      branches:
        include: master
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art                      
      buildName: SampleApp
      buildNumber: 1     
pipelines: 
  - name: shipa_pipeline
    configuration:
      environmentVariables:
        readOnly:
          server: "http://34.105.17.234:8080" 
          user: "bandrade@shipa.io"
          pwd: "shipa2020"
    steps:
      - name: install_shipa_ci
        type: Bash        
        execution:
          onExecute:
            - pip install shipa-ci
 
  - name: deploy_app
    configuration:
      environmentVariables:
        readOnly:
          server: "http://34.105.17.234:8080" 
          user: "bandrade@shipa.io"
          pwd: "shipa2020"
    steps:
      - name: deploying_now
        type: Bash        
        execution:
          onExecute:
            - shipa-ci --server=http://34.105.17.234:8080 --email=bandrade@shipa.io --password=shipa2020 app deploy --app=jfrog
